[Settings]
blow_gravity=0.81632656
global_gravity=0.40816328
patch_ability_categories=on 
remove_modifier_attack_flag=on 
aerial_dodge_patch=on


#Damage Modifier per difficulty.
beginner_party_dmg=150
beginner_enemy_dmg=50
standard_party_dmg=100
standard_enemy_dmg=100
proud_party_dmg=125
proud_enemy_dmg=200
crit_party_dmg=125
crit_enemy_dmg=200

beginner_ap_mult=1
standard_ap_mult=1
proud_ap_mult=1.5
crit_ap_mult=1.5

begginer_hp_mult=1
standard_hp_mult=1
proud_hp_mult=0.5
crit_hp_mult=0.5

begginer_mp_mult=1
standard_mp_mult=1
proud_mp_mult=0.5
crit_mp_mult=0.5

drive_add_mult=1.0
disable_genie_tink_special=on
enable_negative_stats=on
CursorRemain=0,0,0,0,0,5,0,0,0,0,10,0,0,0,14,0,16,17,18
submenu_memory=on
menu_memory=off
repoint_and_extend_btlobj_sheet=on
change_custom_magic_mpdrive_status=off

#Blow_Gravity: Gravity used when hitting an object up in the air.
#Global_Gravity: Gravity used by things like jumps, etc.
#0.40816328 is the default gravity value
#0.81632656 is 2x, mimics PS2 60fps.

#patch_ability_categories: Allows any ability with its Buy value equal to 1 to be counted as a "Support" ability, and be added to the Ability List in forms.
#remove_modifier_attack_flag: Allows you to use Combo Modifiers like Upper Slash/Finishing Leap without having to first hit your attack on an enemy, assuming you have Combo Master on.
#aerial_dodge_patch: Allows you to use Aerial Dodge after attacking in the air.
#drive_add_mult: this is a float value that by default is set to 1.0. Modifying this value will directly multiply the amount of drive earned on-hit.