[Settings]
shopface_fix=on
shop_restrict_fix=on

#shopface_fix: Lets you load the shopface from a file instead of the EXE.
#shop_restrict_fix: Removes restrictions on buying items like magic or forms from the shop.