[Settings]
worldpoint_amount=on
apply_worldsymbol_patch=on
symbol_zz=5024,1,2,3,4
symbol_es=5001,5,6,7,8
symbol_di=0,0,0,0,0
symbol_po=0,0,0,0,0
symbol_wi=0,0,0,0,0
symbol_tr=9999,9,9,9,9
patch_gummiskip=off
halve_gummiship_plans=off
halve_tinyship_plans=off

#Worldpoint_Amount: Changes the number of allowed warp points allowed by the game. 

#apply_worldsymbol_patch:
#Patches the worldmaps warpable "Symbols" to instead be relocated to a different memory address, and expands the number of symbols possible. 
#symbol_xx: Intended for use with the above, this lets you define the following for patching in these new world_symbols.
#Newly added symbols. Format: OBJ_ID, World_ID, bgGroup, Course, PaddingByte
#halve_gummiship_plans and halve_tinyship_plans settings for KH2_Tweaks_Worlds, these will halve the amount of Gummi ship plans/Tiny ship plans that can be made, freeing up about 0x5000 bytes in the save file. Gummiship freed bytes are at Save+0x9530, and there are now 0x3F90 total bytes after this which can be used.