[Settings]
dualwield_forms=0,2,3,0,5,0 
disable_drive_restrictions=on
uncap_form_level=on
apply_pridelands_patches=on
solo_summon_fix=on
valor_growth=0,94,95,96,97
wisdom_growth=0,98,99,100,101
limit_growth=0,0,0,0,0
master_growth=0,102,103,104,105
final_growth=0,106,107,108,109


#Dualwield_Forms: Allows you to specify which forms can dual-wield keyblades.
#Ensure that if you want to exclude a form, you don't just delete it. Replace the form ID with a 0.
#So for example, to exclude Wisdom, Limit, and Antiform from being Dual Wield Forms, write this:
#dualwield_forms=1,0,0,4,5,0

#Disable Drive Restrictions: Removes the restrictions on using Drives requiring party members.

#Uncap Form Level: Allows you to level forms up to the max from the start, without needing other forms

#Pridelands_Patches: Lets you change out form keyblades in Pridelands.

#Solo_Summon_Fix: Makes summons appear right next to you even if you don't have party members.

#form_growth: Changes out the growth abilities you learn/your form learns every other levelup.
